# Generated by Django 5.0.6 on 2024-06-16 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_payment_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 17, 15, 46, 45, 936196, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=7,
            ),
        ),
    ]
