# Generated by Django 5.0.6 on 2024-06-16 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_payment_session_expiry_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 17, 16, 4, 16, 939720, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
