# Generated by Django 5.0.6 on 2024-06-17 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_alter_payment_session_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 18, 12, 0, 30, 938511, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
