# Generated by Django 5.0.6 on 2024-06-15 21:58

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(null=True, upload_to=book.models.book_image_path),
        ),
    ]
