# Generated by Django 5.0.6 on 2024-06-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email_address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="first_name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="second_name",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="second_name"
            ),
        ),
    ]
