# Generated by Django 5.0.6 on 2024-06-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_second_name_alter_user_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="second_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="last name"
            ),
        ),
    ]
